SELECT * FROM customer LIMIT 10;

-- Q1 What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2 Which customer used a discount but still spent more then average purchase amount?

SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3 Which are the top 5 products with the highest average review rating? 
SELECT item_purchased, ROUND(AVG(review_rating),2) AS average_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;

-- Q4 Compare the average purchase amounts between standard and express shipping.
SELECT shipping_type, AVG(purchase_amount) AS average_amount
FROM customer
WHERE shipping_type IN ('standard','Express')
GROUP BY shipping_type;

-- Q5 DO subscribed customers spend more ? compare average spend and total revenue between subscribers and non subscribers

SELECT subscription_status, COUNT(customer_id) AS total_count, AVG(purchase_amount) AS average_spend, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

-- Q6 Which 5 products have the highest percentage of purchase with discounts applies 

SELECT item_purchased,
	(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 END) *100 / COUNT(*)) AS percentage
FROM customer
GROUP BY item_purchased
ORDER BY percentage DESC
LIMIT 5;

-- Q7 Segment customer into new returning and loyal based on their total number of previous purchase and show the count of each segment
WITH customer_type AS (
SELECT  customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New Customer'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Return Customer'
    ELSE 'Loyal'
END AS customer_segment
FROM customer)

SELECT customer_segment, COUNT(*) AS No_of_customer
FROM customer_type
GROUP BY customer_segment;

-- Q8 What are the top 3 most purchase products within each category

WITH item_counts AS (
SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9 ARe customer who are repeat (more than 5 previous purchase) also likely to subscribe

SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10 What is the revenue contribution of each age group

SELECT age_group, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY age_group;

















